#!/bin/bash -x

##########################################################################
#
# Generates a fake CPAN repository of dummy distributions, based on
# specification in META files.  These fake repositories are then used
# for functional testing of Pinto.  Unfortunately, you have to
# understand what is in each of these META files to be able to
# diagnose what is going wrong with the tests.  Perhaps in the future
# we'll be able to declare the specification much closer to where the
# test actually happens.
#
# And by the way, you need to install CPAN::Faker for this to work!
#
##########################################################################

for d in repos/*; do 
    d=`basename $d`; 
    rm -rf repos/$d; 
    cpanfaker -s specs/$d -d repos/$d;
done 

