#!/usr/bin/env perl
use strict;
use warnings;
use Carp;
my $VERSION = '0.0.1';
use Cwd qw< getcwd realpath >;
use File::Basename qw< dirname >;
use File::Spec::Functions qw< catfile >;

my $me = realpath(__FILE__);
my $root = dirname($me);
my $cpanm = catfile($root, 'cpanm');
chdir($ENV{OLDPWD});

my @base_args = (qw< --mirror-only --mirror >, "file://$root", @ARGV);

open my $fh, '|-', $cpanm, @base_args
   or die "open() as fork: $!\n";
binmode $fh, ':raw';

binmode DATA, ':raw';
while ('necessary') {
   my $nread = sysread DATA, my $buf, 4096;
   die "sysread(): $!\n" unless defined $nread;
   last unless $nread;
   print {$fh} $buf
      or die "print(): $!\n";
}

close $fh
   or die "close(): $!\n";


__END__
