#!/usr/bin/env perl
use strict;
use warnings;
use Carp;
my $VERSION = '0.0.1';
use Cwd qw< realpath >;
use File::Basename qw< dirname >;
use File::Spec::Functions qw< catfile >;

my $me = realpath(__FILE__);
my $root = dirname($me);
my $cpanm = './cpanm';
my %config = %{ do "$me.cnf" };

my @args = @ARGV ? @ARGV : @{$config{distros}};
unshift @args, qw< --mirror-only --mirror >, catfile($root, 'repo');
system {$cpanm} $cpanm, @args;

__END__
