#!/usr/bin/env perl

use strict;
use warnings;

use Pinto;
use Try::Tiny;
use Path::Class;
use File::Find::Rule;

#------------------------------------------------------------------------------

my ($cpan_dir, $pinto_dir) = @ARGV;
my $rule = File::Find::Rule->file->name('*.tar.gz')->start("$cpan_dir/authors/id");

#------------------------------------------------------------------------------

open my $log_fh, '>', 'logfile.log' or die $_;

#------------------------------------------------------------------------------

while (my $archive = $rule->match) {

    my $pinto     = Pinto->new(root => $pinto_dir);
    my $dist_path = file($archive)->relative($cpan_dir)->cleanup;
    my $author    = (split '/', $dist_path)[4];

    next if $dist_path->basename =~ /^Acme-BadExample/;          # Hangs
    next if $dist_path->basename =~ /^(syb|ora)?perl-?[\d\.]+/i; # Don't want

    my $msg = "Importing $dist_path from CPAN";
    print "$msg\n";

    my %args = ( archives  => [$archive],
                 author    => $author,
                 message   => $msg,
                 norecurse => 1 );

    try   { $pinto->run(Add => %args) }
    catch { s/(\n.*)//msg; print {$log_fh} "$archive: $_\n" };
}
