#!/bin/bash -x

# Run this command from inside the sql/ directory to generate the
# schema classes.  You must install DBIx::Class::Schema::Loader first.

rm -rf pinto.db

sqlite3 pinto.db < pinto.sql

dbicdump -o dump_directory=../lib \
         -o 'relationship_attrs={ has_many => {cascade_delete => 1} }' \
         Pinto::Schema \
         dbi:SQLite:pinto.db

